# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - uses: s4u/maven-settings-action@v2.3.0
      with:
          servers: |
            [{
                "id": "tippie-repo",
                "username": "${{ secrets.TIPPIE_REPO_USERNAME }}",
                "password": "${{ secrets.TIPPIE_REPO_PASSWORD }}"
            }]

    - name: Publish to Tippie Repo
      run: mvn deploy
        

